// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/openshift/api/monitoring/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAlertOverrides implements AlertOverridesInterface
type FakeAlertOverrides struct {
	Fake *FakeMonitoringV1alpha1
	ns   string
}

var alertoverridesResource = schema.GroupVersionResource{Group: "monitoring.openshift.io", Version: "v1alpha1", Resource: "alertoverrides"}

var alertoverridesKind = schema.GroupVersionKind{Group: "monitoring.openshift.io", Version: "v1alpha1", Kind: "AlertOverrides"}

// Get takes name of the alertOverrides, and returns the corresponding alertOverrides object, and an error if there is any.
func (c *FakeAlertOverrides) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AlertOverrides, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(alertoverridesResource, c.ns, name), &v1alpha1.AlertOverrides{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AlertOverrides), err
}

// List takes label and field selectors, and returns the list of AlertOverrides that match those selectors.
func (c *FakeAlertOverrides) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AlertOverridesList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(alertoverridesResource, alertoverridesKind, c.ns, opts), &v1alpha1.AlertOverridesList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AlertOverridesList{ListMeta: obj.(*v1alpha1.AlertOverridesList).ListMeta}
	for _, item := range obj.(*v1alpha1.AlertOverridesList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested alertOverrides.
func (c *FakeAlertOverrides) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(alertoverridesResource, c.ns, opts))

}

// Create takes the representation of a alertOverrides and creates it.  Returns the server's representation of the alertOverrides, and an error, if there is any.
func (c *FakeAlertOverrides) Create(ctx context.Context, alertOverrides *v1alpha1.AlertOverrides, opts v1.CreateOptions) (result *v1alpha1.AlertOverrides, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(alertoverridesResource, c.ns, alertOverrides), &v1alpha1.AlertOverrides{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AlertOverrides), err
}

// Update takes the representation of a alertOverrides and updates it. Returns the server's representation of the alertOverrides, and an error, if there is any.
func (c *FakeAlertOverrides) Update(ctx context.Context, alertOverrides *v1alpha1.AlertOverrides, opts v1.UpdateOptions) (result *v1alpha1.AlertOverrides, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(alertoverridesResource, c.ns, alertOverrides), &v1alpha1.AlertOverrides{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AlertOverrides), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAlertOverrides) UpdateStatus(ctx context.Context, alertOverrides *v1alpha1.AlertOverrides, opts v1.UpdateOptions) (*v1alpha1.AlertOverrides, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(alertoverridesResource, "status", c.ns, alertOverrides), &v1alpha1.AlertOverrides{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AlertOverrides), err
}

// Delete takes name of the alertOverrides and deletes it. Returns an error if one occurs.
func (c *FakeAlertOverrides) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(alertoverridesResource, c.ns, name, opts), &v1alpha1.AlertOverrides{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAlertOverrides) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(alertoverridesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.AlertOverridesList{})
	return err
}

// Patch applies the patch and returns the patched alertOverrides.
func (c *FakeAlertOverrides) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AlertOverrides, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(alertoverridesResource, c.ns, name, pt, data, subresources...), &v1alpha1.AlertOverrides{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AlertOverrides), err
}
