// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AlertingRuleListerExpansion allows custom methods to be added to
// AlertingRuleLister.
type AlertingRuleListerExpansion interface{}

// AlertingRuleNamespaceListerExpansion allows custom methods to be added to
// AlertingRuleNamespaceLister.
type AlertingRuleNamespaceListerExpansion interface{}
