// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AlertOverridesListerExpansion allows custom methods to be added to
// AlertOverridesLister.
type AlertOverridesListerExpansion interface{}

// AlertOverridesNamespaceListerExpansion allows custom methods to be added to
// AlertOverridesNamespaceLister.
type AlertOverridesNamespaceListerExpansion interface{}
