// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	monitoringv1alpha1 "github.com/openshift/api/monitoring/v1alpha1"
	versioned "github.com/openshift/client-go/monitoring/clientset/versioned"
	internalinterfaces "github.com/openshift/client-go/monitoring/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/openshift/client-go/monitoring/listers/monitoring/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AlertOverridesInformer provides access to a shared informer and lister for
// AlertOverrides.
type AlertOverridesInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.AlertOverridesLister
}

type alertOverridesInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAlertOverridesInformer constructs a new informer for AlertOverrides type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAlertOverridesInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAlertOverridesInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAlertOverridesInformer constructs a new informer for AlertOverrides type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAlertOverridesInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MonitoringV1alpha1().AlertOverrides(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MonitoringV1alpha1().AlertOverrides(namespace).Watch(context.TODO(), options)
			},
		},
		&monitoringv1alpha1.AlertOverrides{},
		resyncPeriod,
		indexers,
	)
}

func (f *alertOverridesInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAlertOverridesInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *alertOverridesInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&monitoringv1alpha1.AlertOverrides{}, f.defaultInformer)
}

func (f *alertOverridesInformer) Lister() v1alpha1.AlertOverridesLister {
	return v1alpha1.NewAlertOverridesLister(f.Informer().GetIndexer())
}
